store/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="home_page"),
    path('produto/<str:url_produto>', views.produto, name='url_produto'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('user.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

store/user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path('', view, name=""),
    path('login', views.Userlogin, name="login"),
    path('register', views.register, name="register"),
]

store/main/models.py
from django.db import models


class Produto(models.Model):
    imagemain = models.ImageField(
        'Imagem Principal', upload_to='images', default='')
    name = models.CharField('Nome', max_length=100)
    descricao = models.TextField('Descrição', max_length=3000, default='')
    price = models.FloatField('Preço', default=0)
    quantidade = models.PositiveIntegerField('Quantidade', default=0)

    def __str__(self):
        return self.name


class ImagesProduto(models.Model):
    image = models.ImageField(
        'Imagem', upload_to='images', default='')
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.produto)

    class Meta:
        verbose_name_plural = "ImagesProduto"


class CoresProduto(models.Model):
    cor = models.CharField('Cor', max_length=40)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.cor)

    class Meta:
        verbose_name_plural = "coresProduto"


class TamanhoProduto(models.Model):
    tamanho = models.CharField('Tamanho', max_length=100)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.tamanho)

    class Meta:
        verbose_name_plural = "TamanhoProduto"

store/user/models.py
from django.db import models

# Create your models here.

store/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email']

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

store/main/views.py
from django.shortcuts import render
from .models import Produto
from django.shortcuts import redirect
from django.http import Http404


def index(request):
    produtos = Produto.objects.all()
    context = {
        'produtos': produtos,
    }
    return render(request, 'home/home.html', context)


def produto(request, url_produto):
    # transformar url em array
    transformArrayUrl = url_produto.split('-')
    # Try para verificar se o id é um numero, caso contrario retonará pagina não encontrada
    try:
        # pegar ultimo elemento do array (id)
        id_produto = int(transformArrayUrl[-1])
    except ValueError:
        raise Http404("Página não encontrada")

    # pegar o tamanho do array
    length_url = len(transformArrayUrl) - 1
    # remover o ultimo elemento do array (id)
    transformArrayUrl.pop(length_url)
    # transformar array em uma String
    nome_produto = ' '.join(transformArrayUrl)

    try:
        produto = Produto.objects.get(
            name=nome_produto, id=id_produto)
    except:
        raise Http404("Página não encontrada")

    context = {
        'produto': produto,
    }
    return render(request, 'home/produto.html', context)

store/user/views.py
from django.shortcuts import render, redirect
from .forms import UserForm
from django.contrib.auth import login
from django.contrib import messages


def Userlogin(request):
    context = {

    }
    return render(request, 'user/login.html', context)


def register(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("home_page")
        messages.error(
            request, "Unsuccessful registration. Invalid information.")

    form = UserForm()

    context = {
        "form": form
    }
    return render(request, 'user/register.html', context)

store/main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-danger ">
        <div class="container-fluid p-2 me-auto">
            <button class=" navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <img src="{% static 'images/menu_7rd7419wnpnc.svg' %}" width="26" alt="menu">
            </button>
            <a class="navbar-brand d-flex align-content-center" href=" {% url 'home_page' %}">
                <img src="{% static 'images/logo_design_xao2o1ax2ziz.svg' %}" width="30" height="30"
                    class="d-inline-block align-text-top">
                <span class="mx-3">SMacias</span>
            </a>
            <div class="order-lg-1 mx-3">
                <img src="{% static 'images/carrinho.svg' %}" width="30" alt="">
                <a href="{% url 'login' %}"><img width="35" src="{% static 'images/user.svg' %}" width="30" alt=""></a>
            </div>


            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mt-4 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active p-2" href="{% url 'home_page' %}">PÁGINA PRINCIPAL</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link p-2" href="#">CATEGORIAS</a>
                    </li>
                </ul>
                <form class="d-flex p-2" role="search">
                    <div class="input-group border border-light border-2 rounded">
                        <span class="input-group-text text-light bg-danger border-0" id="basic-addon1"><img
                                src="{% static 'images/icons8-search.svg' %}" width="24"></span>
                        <input class="form-control bg-danger border-0 rounded search_input" type="text"
                            placeholder="Pesquisar..." aria-label="Username" aria-describedby="basic-addon1">
                    </div>
                </form>
            </div>

        </div>
    </nav>

    <main>

        {% block content %}

        {% endblock %}
    </main>
    <footer class="bg-danger">
        <div class="container-fluid  p-5 items_footer">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">

                <div class="col">
                    <div>
                        <h6>ATENDIMENTO AO CLIENTE</h6>
                        <ul class="list-group ">
                            <li class="list-group-item border-0 bg-danger"><a class="text-light" href="#">Central De
                                    Ajuda</a>
                            </li>
                            <li class="list-group-item border-0 bg-danger"><a class="text-light" href="#">Como
                                    Comprar</a></li>
                            <li class="list-group-item border-0 bg-danger"><a class="text-light" href="#">Devolução E
                                    Reembolso</a></li>
                            <li class="list-group-item border-0 bg-danger"><a class="text-light" href="#">Métodos De
                                    Pagamento</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col">
                    <div>
                        <h6>SOBRE A LOJA</h6>
                        <ul class="list-group ">
                            <li class="list-group-item border-0 bg-danger"><a class="text-light" href="#">Sobre nós</a>
                            </li>
                            <li class="list-group-item border-0 bg-danger"><a class="text-light" href="#">Política de
                                    Privacidade</a></li>
                            <li class="list-group-item border-0 bg-danger"><a class="text-light" href="#">Ofertas
                                    Relâmpago
                                </a></li>
                            <li class="list-group-item border-0 bg-danger"><a class="text-light" href="#">Política da
                                    loja</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col">
                    <div>
                        <h6>PAGAMENTO</h6>
                        <ul class="list-group ">
                            <li class="list-group-item border-0 bg-danger"><a class="text-light" href="#">Central De
                                    Ajuda</a>
                            </li>
                            <li class="list-group-item border-0 bg-danger"><a class="text-light" href="#">Como
                                    Comprar</a></li>
                            <li class="list-group-item border-0 bg-danger"><a class="text-light" href="#">Devolução E
                                    Reembolso</a></li>
                            <li class="list-group-item border-0 bg-danger"><a class="text-light" href="#">Métodos De
                                    Pagamento</a></li>
                        </ul>
                    </div>
                </div>


            </div>

        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    <script type="text/javascript">
        function right() {
            document.getElementById("listp").scrollTo({
                left: 1000,
                behavior: 'smooth'
            })
        }
        function left() {
            document.getElementById("listp").scrollTo({
                left: -1000,
                behavior: 'smooth'
            })
        }
    </script>
</body>

</html>

store/main/templates/home/error404.html
{% extends "base.html" %}
{% block title %}Error 404{% endblock %}

{% block content %}
Error#404
{% endblock %}

store/main/templates/home/home.html
{% extends "base.html" %}
{% block title %}SMacias{% endblock %}

{% block content %}
<div class="container-lg mt-5 mb-5">
    {{ hello }}
    <div class="row row-cols-2 row-cols-sm-3 row-cols-md-4 g-4">
        {% if produtos %}{% for produto in produtos %}
        <div class="col">
            <div class="card border-0">
                <a href="/produto/{{produto.name.split|join:'-'}}-{{produto.id}}">
                    <img src="{{produto.imagemain}}" class="card-img-top" alt="...">

                    <div class="card-body p-0">
                        <h5 class="card-title h6 text-dark">{{produto.name}}</h5>
                        <div>
                            <div>
                                <p class="text-danger h5">R$ {{produto.price}}</p>
                            </div>
                            <div>
                                <p class=" mt-0 mb-0 text-dark">5,6mil Vendidos</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}{% endif %}

    </div>
</div>

<div class="d-flex justify-content-center">
    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item disabled">
                <span class="page-link">Anterior</span>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item active" aria-current="page">
                <span class="page-link">2</span>
            </li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">4</a></li>
            <li class="page-item">
                <a class="page-link" href="#">Próximo</a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

store/main/templates/home/produto.html
{% extends "base.html" %}
{% block title %}SMacias{% endblock %}
{% load static %}
{% block content %}

<div class="container-lg p-4 produto">
    <div class="row g-0 h-100">
        <div class="col-md-6 col-lg-5">
            <div class="card h-100 border-0">
                <div>
                    <img class="w-100" src="{{ produto.imagemain.url }}" alt="">
                </div>
                {% if produto.imagesproduto_set.all %}
                <div class="containerlp">
                    <div onclick="left()"
                        class="controllerLeft d-none d-sm-flex justify-content-center align-items-center">
                        <img src="{% static 'images/left.svg' %}" alt="">
                    </div>
                    <div onclick="right()"
                        class="d-none d-sm-flex controllerRight d-flex justify-content-center align-items-center">
                        <img src="{% static 'images/right.svg' %}" alt="">
                    </div>
                    <div class="d-flex overflow-auto listaproduto" id="listp">
                        <img class="w-25 m-1 p-1" src="{{ produto.imagemain.url }}" alt="">
                        {% for images in produto.imagesproduto_set.all %}
                        <img class="w-25 m-1 p-1" src="{{ images.image.url }}" alt="">
                        {% endfor %}

                    </div>
                </div>
                {% endif %}
            </div>
        </div>

        <div class="col-md-6 col-lg-7 mt-4 mt-md-0">
            <div class="card h-100 border-0 p-sm-0 p-md-4 d-flex justify-content-between">

                <div class="d-flex flex-column">
                    <span class="mb-1"> 0 Vendidos</span>
                    <h2 class="h4">{% if produto %}{{ produto.name }} {% endif %}</h2>

                    <span class="h2 text-danger">R$ {{ produto.price }}</span>

                    <div class="d-flex w-100 mt-2">
                        <img src="{% static 'images/truck.svg' %}" width="26" alt="menu">
                        <div class="d-flex flex-column mx-3">
                            <span>Frete grátis com cupom
                            </span>
                            <span>Para compras acima de R$39,00</span>
                        </div>
                    </div>
                    <!--<div class="d-flex w-100 mt-2">
                        <div class="d-flex flex-column ">
                            <span>Atacado ao Comprar (2 - 9) R$90,12 </span>
                            <span>Comprar (> = 10) R$90,11</span>
                        </div>
                    </div> -->
                    {% if produto.coresproduto_set.all %}
                    <div class="d-flex flex-column w-100 mt-2">
                        <span class="mt-2 mb-2">Cores:</span>
                        <div class="d-flex flex-column ">
                            <select class="form-select" aria-label="Default select example">
                                {% for cor in produto.coresproduto_set.all %}
                                <option value="{{cor.cor}}">{{cor.cor}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    {% endif %}
                    {% if produto.tamanhoproduto_set.all %}
                    <div class="d-flex flex-column w-100 mt-2">
                        <span class="mt-2 mb-2">Tamanho:</span>
                        <div class="d-flex flex-column ">
                            <select class="form-select" aria-label="Default select example">
                                {% for tamanho in produto.tamanhoproduto_set.all %}
                                <option value="{{tamanho.tamanho}}">{{tamanho.tamanho}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    {% endif %}
                    {% if produto %}
                    <div class="d-flex flex-column w-100 mt-2">
                        <span class="mt-2 mb-2">Quantidade:</span>
                        <div class="flex-column ">
                            <input type="number" max="{{produto.quantidade}}" class="form-control" id="replyNumber"
                                min="0" value="0" data-bind="value:replyNumber" />
                        </div>

                        <span class="mt-2 mb-2">{{produto.quantidade}} produtos disponíveis</span>
                    </div>
                    {% endif %}
                </div>
                <div class="mt-2">
                    <button type="button" class="btn btn-success mt-2">COMPRAR</button>
                    <button type="button" class="btn btn-secondary mt-2">ADICIONAR NO CARRINHO</button>
                </div>
            </div>
        </div>
        <div class="mt-4">
            <h3 class="h4">Descrição Do Produto</h3>
            {% if produto.descricao %}
            {{produto.descricao|safe}}
            {% else %}
            <p class="mt-3">Produto sem descrição.</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

store/user/templates/user/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="d-flex justify-content-center">
    <form method="post" class="w-100 p-4" style="max-width: 500px; margin: 150px 0px 150px 0px;">
        <h2>Entre</h2>

        <button type="submit" class="btn btn-primary w-100 mt-3" type="button">Entrar</button>
        <span>Ainda não tem uma conta? <a href="{% url 'register' %}">Cadastrar agora!</a></span>
    </form>
</div>
{% endblock %}

store/user/templates/user/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}
{% block content %}
<div class="d-flex justify-content-center">
    <form method="post" class="w-100 p-4" style="max-width: 500px; margin: 150px 0px 150px 0px;">
        <h2>Cadastrar</h2>
        {% csrf_token %}
        {{form|crispy}}

        <button type="submit" class="btn btn-primary w-100 mt-3" type="button">Entrar</button>
    </form>
</div>
{% endblock %}